COT_URL=tls://tak.example.com:8089
PYTAK_TLS_CLIENT_CERT=/etc/sikw00fcot/sikw00fcot.pem
PYTAK_TLS_CLIENT_KEY=/etc/sikw00fcot/sikw00fcot-key.pem
PYTAK_TLS_CLIENT_CAFILE=/etc/sikw00fcot/sikw00fcot-ca.pem
PYTAK_TLS_DONT_CHECK_HOSTNAME=1
MAV_URL=udpin:0.0.0.0:14550
COT_TYPE=a-u-A-M-H-Q
COT_STALE=120
